### ISSUE TITLE
请问有迅速整理大量网址的工具吗？从Chrome导出的收藏夹

### ISSUE THREAD

**Issue by gotoorder** [netnr/uuid#7]
手动一个个整理的话太费时了，或者开发一个可以直接读取Chrome等浏览器导出的html的功能

**Comment by gotoorder** [comment]
原本收藏夹都放在pinbox平台，现在它收费了，超过300个网址就收藏不了了，我早就超300了，被坑了一把。。。
感觉你这想法挺好的，后续还可以继续开发完善功能，方便大家存放收藏夹

**Comment by netnr** [comment]
好的

**Comment by netnr** [comment]
https://uuid.fun/convertbookmarks
